name: dbt_run_deployment_template

on:
  workflow_call:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true
      environment:
        type: string
        description: 'github environment to get configuration values'
        required: true
        default: prod
      warehouse:
        type: string
        description: 'dbt warehouse'
        required: true
        default: DBT_CLOUD


jobs:
  dbt:
    uses: ./.github/workflows/dbt.yml
    secrets: inherit
    with:
      warehouse: ${{ inputs.warehouse }}
      environment: workflow_${{ inputs.environment }}
      command: ${{ inputs.dbt_command }}

  update_datashare:
    uses: ./.github/workflows/dbt.yml
    needs: dbt
    secrets: inherit
    with:
      warehouse: ${{ inputs.warehouse }}
      environment: workflow_${{ inputs.environment }}
      command: |
        dbt ls -m fsc_utils.datashare._datashare___create_gold
        cnt=$(dbt ls -m fsc_utils.datashare._datashare___create_gold | wc -l )
        if [ $cnt -eq 1 ]; then
          dbt run -m fsc_utils.datashare._datashare___create_gold
        fi