name: dbt_run_template

on:
  workflow_call:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true
      environment:
        type: string
        description: 'github environment to get configuration values'
        required: true
      warehouse:
        type: string
        description: 'dbt warehouse'
        required: true

env:
  USE_VARS: "${{ vars.USE_VARS }}"
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ secrets.DBT_VERSION }}"
  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

  DBT_PROFILES_DIR_VAR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION_VAR: "${{ vars.DBT_VERSION }}"
  ACCOUNT_VAR: "${{ vars.ACCOUNT }}"
  ROLE_VAR: "${{ vars.ROLE }}"
  USER_VAR: "${{ vars.USER }}"
  PASSWORD_VAR: "${{ vars.PASSWORD }}"
  REGION_VAR: "${{ vars.REGION }}"
  DATABASE_VAR: "${{ vars.DATABASE }}"
  SCHEMA_VAR: "${{ vars.SCHEMA }}"

  WAREHOUSE: "${{ inputs.warehouse }}"
  
jobs:
  run_dbt_jobs_vars:
    if: github.env.USE_VARS == 'TRUE'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ env.DBT_VERSION_VAR }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          ${{ inputs.dbt_command }}

  run_dbt_jobs_secrets:
    if: github.job.run_dbt_jobs_vars.result == 'skipped'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ env.DBT_VERSION }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          ${{ inputs.dbt_command }}
        
  dump_vars:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: log all env vars
        run: |
          echo "USE_VARS: $USE_VARS"
          echo "DBT_PROFILES_DIR: $DBT_PROFILES_DIR"
          echo "DBT_VERSION: $DBT_VERSION"
          echo "ACCOUNT: $ACCOUNT"
          echo "ROLE: $ROLE"
          echo "USER: $USER"
          echo "REGION: $REGION"
          echo "DATABASE: $DATABASE"
          echo "SCHEMA: $SCHEMA"
          echo "WAREHOUSE: $WAREHOUSE"
          echo "DBT_PROFILES_DIR_VAR: $DBT_PROFILES_DIR_VAR"
          echo "DBT_VERSION_VAR: $DBT_VERSION_VAR"
          echo "ACCOUNT_VAR: $ACCOUNT_VAR"
          echo "ROLE_VAR: $ROLE_VAR"
          echo "USER_VAR: $USER_VAR"
          echo "REGION_VAR: $REGION_VAR"
          echo "DATABASE_VAR: $DATABASE_VAR"
          echo "SCHEMA_VAR: $SCHEMA_VAR"
      
      - name: log status
        run: |
          echo "${{ github.job.run_dbt_jobs_vars.result }}"
          echo "${{ github.job.run_dbt_jobs_secrets.result }}"
