name: dbt_run_template

on:
  workflow_call:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true
      environment:
        type: string
        description: 'github environment to get configuration values'
        required: true
      warehouse:
        type: string
        description: 'dbt warehouse'
        required: true

env:
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR || secrets.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION || secrets.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT || secrets.ACCOUNT }}"
  ROLE: "${{ vars.ROLE || secrets.ROLE }}"
  USER: "${{ vars.USER || secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION || secrets.REGION }}"
  DATABASE: "${{ vars.DATABASE || secrets.DATABASE }}"
  WAREHOUSE: "${{ inputs.warehouse }}"
  SCHEMA: "${{ vars.SCHEMA || secrets.SCHEMA }}"
  
jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ env.DBT_VERSION }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          ${{ inputs.dbt_command }}