name: dbt_run_template

on:
  workflow_call:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true
      environment:
        type: string
        description: 'github environment to get configuration values'
        required: true
      warehouse:
        type: string
        description: 'dbt warehouse'
        required: true

env:
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ secrets.DBT_VERSION }}"
  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

  DBT_PROFILES_DIR_VAR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION_VAR: "${{ vars.DBT_VERSION }}"
  ACCOUNT_VAR: "${{ vars.ACCOUNT }}"
  ROLE_VAR: "${{ vars.ROLE }}"
  USER_VAR: "${{ vars.USER }}"
  PASSWORD_VAR: "${{ vars.PASSWORD }}"
  REGION_VAR: "${{ vars.REGION }}"
  DATABASE_VAR: "${{ vars.DATABASE }}"
  SCHEMA_VAR: "${{ vars.SCHEMA }}"

  WAREHOUSE: "${{ inputs.warehouse }}"
  
jobs:
  run_dbt_jobs_vars:
    if: github.env.DATABASE_VAR != ''
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ env.DBT_VERSION_VAR }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          ${{ inputs.dbt_command }}

  run_dbt_jobs_secrets:
    if: github.job.run_dbt_jobs_vars.result == 'skipped'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ env.DBT_VERSION }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          ${{ inputs.dbt_command }}
        