name: dbt_run_template

on:
  workflow_call:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true
      environment:
        type: string
        description: 'github environment to get configuration values'
        required: true
        default: prod
      warehouse:
        type: string
        description: 'dbt warehouse'
        required: true
        default: DBT_CLOUD

jobs:
  run_dbt_jobs:
    uses: ./.github/workflows/dbt.yml
    secrets: inherit
    with:
      warehouse: ${{ inputs.warehouse }}
      environment: workflow_${{ inputs.environment }}
      command: ${{ inputs.dbt_command }}